SoftwareProjects/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('login.urls')),
    path('house/',include('house.urls',namespace='house')),
    path('rent/',include('rent.urls')),
    path('repair/',include('repair.urls')),
]

house/urls.py
from django.urls import path, include
from . import views

app_name = 'house'
urlpatterns=[
    path('detail/<int:house_id>/',views.detail,name='detail'),
]

rent/urls.py
from django.urls import path, include
from . import views

urlpatterns=[
    path('search/',views.search,name='search'),
]

rent/models.py
from django.db import models

class rentOrder(models.Model):

    type=(
        ("short","短期"),
        ("long","长期")

    )

    begintime = models.DateField(auto_now_add=True,verbose_name="开始时间")
    overtime = models.DateField(default=None,verbose_name="结束时间")
    rent_ownUser = models.ForeignKey("login.User",on_delete=models.CASCADE,related_name='rent_ownUser',verbose_name="房东",default=None)
    rent_paidUser = models.ForeignKey("login.User",on_delete=models.CASCADE,related_name='rent_paidUser',verbose_name="房客",default=None)
    house = models.ForeignKey("house.house",on_delete=models.CASCADE,default=None)
    judge = models.BooleanField(verbose_name="审核结果",default=False)
    type = models.CharField(verbose_name="类型",max_length=32,choices=type)

rent/views.py
import hashlib
import json

from django.core.paginator import Paginator
from django.shortcuts import render, HttpResponse
from django.shortcuts import redirect
from django.http import StreamingHttpResponse, JsonResponse
from django.urls import reverse
from . import models as rent_models
from . import forms
from house.models import house
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import FileResponse

def search(request):
    if request.method == "GET":
        houses = request.session.get('houses',None)
        house_list = house.objects.all()
        flag = 1
        for i in houses:
            print(i)
            print(flag)
            if i != 0:
                if flag == 1:
                    if i == 1:
                        pass
                    elif i == 2:
                        house_list = house_list.filter(area='ChaoYang')
                    elif i == 3:
                        house_list = house_list.filter(area='HaiDian')
                    elif i == 4:
                        house_list = house_list.filter(area='ChangPing')
                elif flag == 2:
                    if i == 1:
                        house_list = house_list.filter(rental__lte=1000)
                    elif i == 2:
                        house_list = house_list.filter(rental__gt=1000,rental__lte=1500)
                    elif i == 3:
                        house_list = house_list.filter(rental__gt=1500, rental__lte=2000)
                    elif i == 4:
                        house_list = house_list.filter(rental__gt=2000,rental__lte=3000)
                    elif i == 5:
                        house_list = house_list.filter(rental__gt=3000)
                elif flag == 3:
                    if i == 1:
                        house_list = house_list.filter(type='single')
                    elif i == 2:
                        house_list = house_list.filter(type='double')
                    elif i == 3:
                        house_list = house_list.filter(type='triple')
                    elif i == 4:
                        house_list = house_list.filter(type='quad')
                elif flag == 4:
                    if i == 1:
                        house_list = house_list.filter(elevator=True)
                    elif i == 2:
                        house_list = house_list.filter(elevator=False)
            elif i == 0:
                flag += 1
            if flag == 6:
                keyword = request.session.get('keyword', None)
                print(keyword)
                if keyword:
                    house_list = house.objects.filter(housename__contains=keyword)


    if request.method == "POST":
        house_list = house.objects.all()
        houses = []
        if 'area' in request.POST:
            areas = request.POST.getlist('area',[])
            print('areas')
            for i in range(0,len(areas)):
                print (areas[i])
                if areas[i] == '1':
                    houses.append(1)
                elif areas[i] == '2':
                    houses.append(2)
                    house_list = house_list.filter(area='ChaoYang')
                elif areas[i] == '3':
                    houses.append(3)
                    house_list = house_list.filter(area='HaiDian')
                elif areas[i] == '4':
                    houses.append(4)
                    house_list = house_list.filter(area='ChangPing')
        houses.append(0)
        if 'rental' in request.POST:
            rentals = request.POST.getlist('rental',[])
            print('rentals')
            for i in range(0,len(rentals)):
                print(rentals[i])
                if rentals[i] == '1':
                    houses.append(1)
                    house_list = house_list.filter(rental__lte=1000)
                elif rentals[i] == '2':
                    houses.append(2)
                    house_list = house_list.filter(rental__gt=1000,rental__lte=1500)
                elif rentals[i] == '3':
                    houses.append(3)
                    house_list = house_list.filter(rental__gt=1500, rental__lte=2000)
                elif rentals[i] == '4':
                    houses.append(4)
                    house_list = house_list.filter(rental__gt=2000,rental__lte=3000)
                elif rentals[i] == '5':
                    houses.append(5)
                    house_list = house_list.filter(rental__gt=3000)
        houses.append(0)
        if 'type' in request.POST:
            types = request.POST.getlist('type',[])
            print('types')
            for i in range(0,len(types)):
                print(types[i])
                if types[i] == '1':
                    houses.append(1)
                    house_list = house_list.filter(type='single')
                elif types[i] == '2':
                    houses.append(2)
                    house_list = house_list.filter(type='double')
                elif types[i] == '3':
                    houses.append(3)
                    house_list = house_list.filter(type='triple')
                elif types[i] == '4':
                    houses.append(4)
                    house_list = house_list.filter(type='quad')
        houses.append(0)
        if 'elevator' in request.POST:
            elevators = request.POST.getlist('elevator', [])
            print('elevators')
            for i in range(0, len(elevators)):
                print(elevators[i])
                if elevators[i] == '1':
                    houses.append(1)
                    house_list = house_list.filter(elevator=True)
                elif elevators[i] == '2':
                    houses.append(2)
                    house_list = house_list.filter(elevator=False)
        houses.append(0)
        if 'keyword' in request.POST:
            keyword = request.POST.get('keyword')
            print('keyword')
            house_list = house.objects.filter(housename__contains=keyword)
            request.session['keyword'] = keyword
            houses.append(0)
        request.session['houses'] = houses

    house_list = house_list.order_by('id')
    paginator = Paginator(house_list,2)
    try:
        page_num = request.GET.get('page',1)
        page = paginator.page(page_num)
    except PageNotAnInteger as e:
        # 不是整数返回第一页数据
        page = paginator.page('1')
        page_num = 1
    except EmptyPage as e:
        # 当参数页码大于或小于页码范围时,会触发该异常
        print('EmptyPage:{}'.format(e))
        if int(page_num) > paginator.num_pages:
            # 大于 获取最后一页数据返回
            page = paginator.page(paginator.num_pages)
        else:
            # 小于 获取第一页
            page = paginator.page(1)

        # 这部分是为了再有大量数据时，仍然保证所显示的页码数量不超过10，
    page_num = int(page_num)
    if page_num < 6:
        if paginator.num_pages <= 10:
            pageRange = range(1, paginator.num_pages + 1)
        else:
            pageRange = range(1, 11)
    elif (page_num >= 6) and (page_num <= paginator.num_pages - 5):
        pageRange = range(page_num - 5, page_num + 5)
    else:
        pageRange = range(paginator.num_pages - 9, paginator.num_pages + 1)


    return render(request,'rent/search.html',locals())
#TODO:点击下一页,搜索集变为all();keyword


def download_template(request):
    file = open('static/files/hetong.docx', 'rb')
    response = FileResponse(file)
    response['Content-Type'] = 'application/octet-stream'
    response['Content-Disposition'] = 'attachment;filename="BatchPayTemplate.xls"'
    return response

rent/templates/rent/rent.html
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <title>青年租房网站</title>
    <link rel="stylesheet" href="../static/css/bootstrap.min.css">
	<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="../static/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="../static/css/rent.css">
    <style>
        @font-face{
          font-family: pacifico;
            src:url("../static/fonts/pacifico.woff");
        }
    </style>
</head>
<body>
    <!-- 导航栏 -->
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="www.baidu.com">网站名</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li><a href="#">首页</a></li>
                    <li class="active"><a href="#">租房</a></li>
                    <li><a href="#">我有房租</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!--搜索框-->
    <div class="container">
        <form method="post"><!--没有写action,我想要在同一页面下展示查找到的房源-->
            <div class="form-inline col-lg-12" style="padding: 0">
                <input type="text" class="form-control input-lg" placeholder="请输入区域、商圈或小区名开始找房" style="font-family: 仿宋;font-size: medium;width:94%">
                <input type="submit" class="btn btn-default" style="width: 5%;height: 43px;background-color: #eeeeee" value="查询">
            </div>
        </form>
    </div>
    <br>
    <!--筛选条件-->
    <div class="container">
        <div class="filter">
            <form role="form" method="post"> <!--这里也没有写action，也是想在同一页面下展示查找到的房源-->
                {% csrf_token %}
                <div class="form-group"><span style="font-weight: bolder">区域：</span> <!--变量名为name,可能是多个值-->
                    <label class="checkbox-inline">
                        <input type="checkbox" name="area">不限
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="area">朝阳区
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="area">海淀区
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="area">昌平区
                    </label>
                </div>
                <div class="form-group"><span style="font-weight: bolder">方式：</span><!--变量名为method,可能是多个值-->
                    <label class="checkbox-inline">
                        <input type="checkbox" name="method">不限
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="method">合租
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="method">整租
                    </label>
                </div>
                <div class="form-group"><span style="font-weight: bolder">租金：</span><!--变量名为price,可能是多个值-->
                    <label class="checkbox-inline" name="price">
                        <input type="checkbox">≤1000元
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="price">1000-1500元
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="price">1500-2000元
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="price">2000-3000元
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="price">≥3000元
                    </label>
                </div>
                <div class="form-group"><span style="font-weight: bolder">户型：</span><!--变量名为houseType,可能是多个值-->
                    <label class="checkbox-inline">
                        <input type="checkbox" name="houseType">单人间
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="houseType">双人间
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="houseType">三人间
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="houseType">四人间
                    </label>
                </div>
                <div class="form-group"><span style="font-weight: bolder">电梯：</span><!--变量名为elevator,可能是多个值-->
                    <label class="checkbox-inline">
                        <input type="checkbox" name="elevator">有电梯
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="elevator">无电梯
                    </label>
                </div>
                <div class="col-lg-2 col-md-2 col-lg-offset-8 col-md-offset-8">
                    <button type="submit" class="btn" >查找房源</button>
                </div>
                <div class="col-lg-2 col-md-2">
                    <button type="reset" class="btn" >清空条件</button>
                </div>
            </form>
        </div>
    </div>
    <br>
    <!--展示房源信息，应该是有多个page，每个page有多个item,应当安排一个默认page，作为没有搜索条件时的显示-->
    <div class="container">
        <ul class="col-lg-12" style="list-style: none" >
            {% for item in page %}
            <li class="col-lg-12">
                <div class="col-lg-3 col-md-3">
                    <div class="thumbnail">
                        <a href="{% url 'houses:detail' houses_id=item.object.id %}">
                            <img src="{% static item.image %}">
                        </a>
                    </div>
                </div>
                <div class="col-lg-9 col-md-9">
                    <div class="caption">
                        <div class="col-lg-6">
                            <a class="h2" href="{%url 'houses:detail' house_id=item.object.id %}">{{ item.object.area }}/{{ item.object.houseType }}</a>
                        </div>
                        <span class="price">{{ item.object.price }}元</span>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="container">
        <div class="col-lg-6 col-md-6 col-lg-offset-10 col-md-offset-6">
            <ul class="pagination">
            {% if page.has_previous %}
                <a href="#">&laquo;</a>  <!--此处的跳转不清楚写什么-->
            {% endif %}
            {% for pindex in paginator.page_range %}
                {% if pindex==page.number %}
                    <a href="#" class="active">{{ pindex }}</a>
                {% else %}
                    <a href="#">{{ pindex }}</a>
                {% endif %}
            {% endfor %}
            {% if page.has_next %}
                <a href="#">&raquo;</a>
            {% endif %}
            </ul>
        </div>
    </div>
    <div class="jumbotron text-center" style="margin-bottom:0">
        <p>底部内容</p>
    </div>
</body>
</html>

rent/templates/rent/search.html
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <title>青年租房网站</title>
    <link rel="stylesheet" href="/static/css/search/bootstrap.min.css">
	<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="/static/js/search/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/css/search/rent.css">
    <style>
        @font-face{
          font-family: pacifico;
            src:url("/static/fonts/pacifico.woff");
        }
    </style>
</head>
<body>
    <!-- 导航栏 -->
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="www.baidu.com">网站名</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li><a href="#">首页</a></li>
                    <li class="active"><a href="#">租房</a></li>
                    <li><a href="#">我有房租</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!--搜索框-->
    <div class="container">
        <form method="post" action="{% url 'search'%}"><!--没有写action,我想要在同一页面下展示查找到的房源-->
            {% csrf_token %}
            <div class="form-inline col-lg-12" style="padding: 0">
                <input type="text"name="keyword" class="form-control input-lg" placeholder="请输入区域、商圈或小区名开始找房" style="font-family: 仿宋;font-size: medium;width:94%">
                <input type="submit" class="btn btn-default" style="width: 5%;height: 43px;background-color: #eeeeee" value="查询" name="关键字">
            </div>
        </form>
    </div>
    <br>
    <!--筛选条件-->
    <div class="container">
        <div class="filter">
            <form role="form" method="post" action="{% url 'search'%}"> <!--这里也没有写action，也是想在同一页面下展示查找到的房源-->
                {% csrf_token %}
                <div class="form-group"><span style="font-weight: bolder">区域：</span> <!--变量名为name,可能是多个值-->
                    <label class="checkbox-inline">
                        <input type="checkbox" name="area" value="1">不限
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="area" value="2">朝阳区
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="area" value="3">海淀区
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="area" value="4">昌平区
                    </label>
                </div>
                <div class="form-group"><span style="font-weight: bolder">租金：</span><!--变量名为price,可能是多个值-->
                    <label class="checkbox-inline" >
                        <input type="checkbox" name="rental" value="1">≤1000元
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="rental" value="2">1000-1500元
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="rental" value="3">1500-2000元
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="rental" value="4">2000-3000元
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="rental" value="5">≥3000元
                    </label>
                </div>
                <div class="form-group"><span style="font-weight: bolder">户型：</span><!--变量名为houseType,可能是多个值-->
                    <label class="checkbox-inline">
                        <input type="checkbox" name="type" value="1">单人间
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="type" value="2">双人间
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="type" value="3">三人间
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="type" value="4">四人间
                    </label>
                </div>
                <div class="form-group"><span style="font-weight: bolder">电梯：</span><!--变量名为elevator,可能是多个值-->
                    <label class="checkbox-inline">
                        <input type="checkbox" name="elevator" value="1">有电梯
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="elevator" value="2">无电梯
                    </label>
                </div>
                <div class="col-lg-2 col-md-2 col-lg-offset-8 col-md-offset-8">
                    <button type="submit" class="btn" >查找房源</button>
                </div>
                <div class="col-lg-2 col-md-2">
                    <button type="reset" class="btn" >清空条件</button>
                </div>
            </form>
        </div>
    </div>
    <br>
    <!--展示房源信息，应该是有多个page，每个page有多个item,应当安排一个默认page，作为没有搜索条件时的显示-->
    <div class="container">
        <ul class="col-lg-12" style="list-style: none" >
            {% for house in page %}
            <li class="col-lg-12">
                <div class="col-lg-3 col-md-3">
                    <div class="thumbnail">
                        <a href="{% url 'house:detail' house_id=house.id %}">
                            <img src="{% static house.image %}">
                        </a>
                    </div>
                </div>
                <div class="col-lg-9 col-md-9">
                    <div class="caption">
                        <div class="col-lg-6">
                            <a class="h2" href="{%url 'house:detail' house_id=house.id %}">{{ house.housename }}/{{ house.type }}</a>
                        </div>
                        <span class="price">{{ house.rental }}元</span>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="container">
        <div class="col-lg-6 col-md-6 col-lg-offset-10 col-md-offset-6">
            <ul class="pagination">

            {% if page.has_previous %}
                <a href="?page={{ page.previous_page_number }}">&laquo;</a>  <!--此处的跳转不清楚写什么-->
            {% endif %}

            {% for pindex in pageRange %}
                {% if pindex == current_num %}
                    <a href="?page={{ pindex }}" class="active">{{ pindex }}</a>
                {% else %}
                    <a href="?page={{ pindex }}">{{ pindex }}</a>
                {% endif %}
            {% endfor %}

            {% if page.has_next %}
                <a href="?page={{ page.next_page_number }}">&raquo;</a>
            {% endif %}
            </ul>
        </div>
    </div>
    <div class="jumbotron text-center" style="margin-bottom:0">
        <p>底部内容</p>
    </div>
</body>
</html>